services:
#    oc_search.example:
#        class: OC\SearchBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.gitrepo:
        class: OC\SearchBundle\Gitrepo
        arguments:
            - '@csa_guzzle.client.gitrepo'
            - '@jms_serializer'
