app:
    resource: '@AppBundle/Controller/'
    type: annotation

# import routes from a controller class
result:
    resource: "@OCSearchBundle/Controller/ResultController.php"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc